// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyrOIzd51wlXpuYRYGUNaN8ChPbdAM-pQ',
    appId: '1:797651044730:web:10532089dfaef49341eec3',
    messagingSenderId: '797651044730',
    projectId: 'trainingsplanner-bc9ff',
    authDomain: 'trainingsplanner-bc9ff.firebaseapp.com',
    storageBucket: 'trainingsplanner-bc9ff.firebasestorage.app',
    measurementId: 'G-NT8S14C726',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_PuMiIj0gMIAqbZ42876KWtVZRCRcPPw',
    appId: '1:797651044730:android:fb326fc096bfa08c41eec3',
    messagingSenderId: '797651044730',
    projectId: 'trainingsplanner-bc9ff',
    storageBucket: 'trainingsplanner-bc9ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1CRnLSXF5_-hh6_qjKWMLlKizNLbpYAo',
    appId: '1:797651044730:ios:93ce396e40b07d5841eec3',
    messagingSenderId: '797651044730',
    projectId: 'trainingsplanner-bc9ff',
    storageBucket: 'trainingsplanner-bc9ff.firebasestorage.app',
    iosBundleId: 'com.example.trainingplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1CRnLSXF5_-hh6_qjKWMLlKizNLbpYAo',
    appId: '1:797651044730:ios:93ce396e40b07d5841eec3',
    messagingSenderId: '797651044730',
    projectId: 'trainingsplanner-bc9ff',
    storageBucket: 'trainingsplanner-bc9ff.firebasestorage.app',
    iosBundleId: 'com.example.trainingplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyrOIzd51wlXpuYRYGUNaN8ChPbdAM-pQ',
    appId: '1:797651044730:web:0b6fee407514e7c941eec3',
    messagingSenderId: '797651044730',
    projectId: 'trainingsplanner-bc9ff',
    authDomain: 'trainingsplanner-bc9ff.firebaseapp.com',
    storageBucket: 'trainingsplanner-bc9ff.firebasestorage.app',
    measurementId: 'G-5MT2CRWP5D',
  );

}